- type: liteapks
  name: via-browser
  version: 6.8.0
  url: https://liteapks.com/download/via-browser-99349
- type: liteapks
  name: hiedu-calculator-pro
  version: 1.8.0
  url: https://liteapks.com/download/hiedu-calculator-pro-309007
- type: liteapks
  name: telegram
  version: 12.1.1
  url: https://liteapks.com/download/telegram-810
- type: github
  name: breezy-weather/breezy-weather
  version: v6.0.12
  url: https://github.com/breezy-weather/breezy-weather/releases/tag/v6.0.12
- type: github
  name: InfinityLoop1308/PipePipe
  version: v4.7.5
  url: https://github.com/InfinityLoop1308/PipePipe/releases/tag/v4.7.5
- type: github
  name: XayahSuSuSu/Android-DataBackup
  version: 2.0.12
  url: https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/2.0.12
- type: github
  name: bmax121/APatch
  version: "11142"
  url: https://github.com/bmax121/APatch/releases/tag/11142
- type: github
  name: gkd-kit/gkd
  version: v1.11.1
  url: https://github.com/gkd-kit/gkd/releases/tag/v1.11.1
- type: github
  name: gedoor/legado
  version: "3.25"
  url: https://github.com/gedoor/legado/releases/tag/3.25
- type: github
  name: aistra0528/Hail
  version: v1.9.0
  url: https://github.com/aistra0528/Hail/releases/tag/v1.9.0
- type: github
  name: ankidroid/Anki-Android
  version: v2.22.3
  url: https://github.com/ankidroid/Anki-Android/releases/tag/v2.22.3
- type: github
  name: obsidianmd/obsidian-releases
  version: v1.10.3
  url: https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.10.3
- type: github
  name: bitwarden/android
  version: v2025.10.1-bwpm
  url: https://github.com/bitwarden/android/releases/tag/v2025.10.1-bwpm
- type: github
  name: gedoor/legado
  version: "3.25"
  url: https://github.com/gedoor/legado/releases/tag/3.25
- type: github
  name: SagerNet/sing-box
  version: v1.12.12
  url: https://github.com/SagerNet/sing-box/releases/tag/v1.12.12
- type: liteapks
  name: mt-manager
  version: 2.19.2
  url: https://liteapks.com/download/mt-manager-2135
- type: github
  name: NitroRCr/AIaW
  version: v1.8.5
  url: https://github.com/NitroRCr/AIaW/releases/tag/v1.8.5
- type: github
  name: Jimex/DictTango-Android
  version: v2.3.4.6
  url: https://github.com/Jimex/DictTango-Android/releases/tag/v2.3.4.6
- type: github
  name: lollipopkit/flutter_server_box
  version: v1.0.1270
  url: https://github.com/lollipopkit/flutter_server_box/releases/tag/v1.0.1270
