- type: liteapks
  name: via-browser
  version: 6.8.0
  url: https://liteapks.com/download/via-browser-99349
- type: liteapks
  name: hiedu-calculator-pro
  version: 1.8.1
  url: https://liteapks.com/download/hiedu-calculator-pro-309007
- type: liteapks
  name: telegram
  version: 12.2.10
  url: https://liteapks.com/download/telegram-810
- type: github
  name: breezy-weather/breezy-weather
  version: v6.0.12
  url: https://github.com/breezy-weather/breezy-weather/releases/tag/v6.0.12
- type: github
  name: InfinityLoop1308/PipePipe
  version: v4.7.6
  url: https://github.com/InfinityLoop1308/PipePipe/releases/tag/v4.7.6
- type: github
  name: XayahSuSuSu/Android-DataBackup
  version: 2.0.12
  url: https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/2.0.12
- type: github
  name: bmax121/APatch
  version: "11142"
  url: https://github.com/bmax121/APatch/releases/tag/11142
- type: github
  name: gkd-kit/gkd
  version: v1.11.6
  url: https://github.com/gkd-kit/gkd/releases/tag/v1.11.6
- type: github
  name: HapeLee/legado-with-MD3
  version: 3.26.4
  url: https://github.com/HapeLee/legado-with-MD3/releases/tag/3.26.4
- type: github
  name: aistra0528/Hail
  version: v1.9.0
  url: https://github.com/aistra0528/Hail/releases/tag/v1.9.0
- type: github
  name: ankidroid/Anki-Android
  version: v2.23.1
  url: https://github.com/ankidroid/Anki-Android/releases/tag/v2.23.1
- type: github
  name: obsidianmd/obsidian-releases
  version: v1.10.6
  url: https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.10.6
- type: github
  name: bitwarden/android
  version: v2025.12.0-bwpm
  url: https://github.com/bitwarden/android/releases/tag/v2025.12.0-bwpm
- type: github
  name: SagerNet/sing-box
  version: v1.12.13
  url: https://github.com/SagerNet/sing-box/releases/tag/v1.12.13
- type: liteapks
  name: mt-manager
  version: 2.19.4-clone
  url: https://liteapks.com/download/mt-manager-2135
- type: github
  name: Jimex/DictTango-Android
  version: v2.3.5.3
  url: https://github.com/Jimex/DictTango-Android/releases/tag/v2.3.5.3
- type: liteapks
  name: daremote
  version: 5.7.5
  url: https://liteapks.com/download/daremote-690973
- type: liteapks
  name: question-ai
  version: 3.3.26
  url: https://liteapks.com/download/question-ai-366272
